version: "3.8"

networks:
  petclinic:
    driver: bridge

services:

  app:

    image: phigor/petclinic:dev
 
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:8080

    networks:
      - petclinic

    links:
      - db:db

    depends_on:
      - db

    environment:
      - SPRING_PROFILES_ACTIVE=mysql

  db:

    image: mysql:5.7

    networks:
      - petclinic      

    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic

